include:
  - project: 'cmp-common/cmp-build-common'
    ref: 'release/2.10'
    file: 'gitlab-ci-template.yaml'

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

stages:
  - prepare
  - test
  - package

cache:
  key: "pip-$CI_JOB_IMAGE"
  paths:
    - .cache/pip/

generate-version:
  extends: .determine-build-version
  stage: prepare

python-test:
  stage: test
  image: ${DOCKER_HUB_PROXY}library/python:3.12
  before_script:
    - mkdir -p reports
    - python -c "import sys; print(sys.version)"
    - python -m pip install --upgrade pip
    - pip install -r requirements.txt
  script:
    - ruff format --check
    - ruff check --output-format=gitlab > reports/code-quality-report.json
    - SSZ_DB_TYPE=mock python -m pytest --doctest-modules --junitxml=reports/unittest-results.xml tests/unit
  variables:
    HTTP_PROXY: "${HTTP_PROXY}"
    HTTPS_PROXY: "${HTTPS_PROXY}"
    NO_PROXY: "${NO_PROXY}"
  artifacts:
    when: always
    expire_in: 3 days
    paths:
      - reports/
    reports:
      junit: reports/unittest-results.xml
      codequality: reports/code-quality-report.json

# If you want the integration tests like in the GitHub Actions workflow, enable this job:
# python-integration-test:
#   stage: test
#   image: python:3.12
#   before_script:
#     - python -c "import sys; print(sys.version)"
#     - python -m pip install --upgrade pip
#     - pip install -r requirements.txt
#   script:
#     - python -m pytest --container-scope=session --doctest-modules --junitxml=reports/integration-test-results.xml tests/integration
#   artifacts:
#     when: always
#     expire_in: 3 days
#     paths:
#       - reports/
#     reports:
#       junit: reports/integration-test-results.xml