[DEFAULT]
# Database Settings
db_type = mssql
db_host = 127.0.0.1
db_dbname = ssz_hdb_int
db_user = root
db_password = root

# Logging
log.level = DEBUG
log.format = %(asctime)s [%(env)s] %(levelname)-8s (%(name)s) - %(message)s
log.stdout = yes
log.file = no
log.file.name = ./pipeline.log

# Pipeline-Settings
optimized = false
output_path = ./output/
template_output_path = ./output/triples/
compression_output_path = ./output/compressed/

template_path = ./pipeline/templates/
start_signal_folder = //szh.loc/ssz/applikationen/HDB_Dropzone/INT/Test/Pipeline

[test]
log.level = DEBUG
output_path = ./output/

[local]
log.level = DEBUG
start_signal_folder = ./output/

[int]
log.level = INFO
log.file = yes
log.file.name = ./pipeline_int_%Y%m%d.log
optimized = true
only_vb_cubes = false
start_signal_folder = //szh.loc/ssz/applikationen/HDB_Dropzone/INT/Test/Pipeline

[prod]
log.level = INFO
log.file = yes
log.file.name = ./pipeline_prod_%Y%m%d.log
optimized = true
only_vb_cubes = false
start_signal_folder = //szh.loc/ssz/applikationen/HDB_Dropzone/PROD/Final/Pipeline

