[DEFAULT]
# Database Settings
db_type = mssql
db_host = 127.0.0.1
db_dbname = ssz_hdb_int
db_user = root
db_password = root

# Logging
log.level = DEBUG
log.format = %(asctime)s [%(env)s] %(levelname)-8s (%(name)s) - %(message)s
log.stdout = yes
log.file = yes
log.file.name = ./pipeline.log

db = ${SSZ_DB_TYPE}
optimized = false
output_path = /out/
template_output_path = ./output/triples/
compression_output_path = ./output/compressed/
template_path = ./pipeline/templates/

logger.filepath = logs
logger.filename = pipeline_%Y%m%d.log
logger.log_level = DEBUG

mysql_host = localhost
mysql_database = hdb
mysql_user = pipeline
mysql_password = pipeline

mssql_host = xxx
mssql_user = xxx
mssql_password = xxx
mssql_database = xxx

fuseki_endpoint = http://localhost:3030
fuseki_dataset = ssz
fuseki_graph = default
fuseki_username = admin
fuseki_password = pipeline

stardog_database = lindas
stardog_endpoint = https://stardog-test.cluster.ldbar.ch
stardog_username = ssz
stardog_password = tvIgsdce3aM5sQEtuFuw2785aEf79h2P
stardog_graph_uri = https://lindas.admin.ch/stadtzuerich
stardog_cert_path = ./stardog-test.cluster.ldbar.ch.crt

start_signal_folder = //szh.loc/ssz/applikationen/HDB_Dropzone/INT/Test/Pipeline

[test]
logger.log_to_file = false
output_path = ./output/

[local]
logger.log_to_file = false

[int]

[prod]
logger.log_level = INFO


