DROP TABLE IF EXISTS dbo.pipe_HDB_TEST;

GO

SELECT
    GESAMTCODE,
    ZEIT,
    JAHR,
    CUBEID,
    KENNZAHL,
    WERT,
    DATENSTATUS,
    ANZ_GRUPPEN,
    REFERENZNUMMER,
    RECORDSTATUS,
    CAST(NULL AS VARBINARY) as hash,
    DATENSTAND,
    PUBLIKATIONSSTATUS,
    DIFFUSIONSID
INTO dbo.pipe_HDB_TEST
FROM dbo.HDB_TEST;